export const UPLOAD_PICTURE = "UPLOAD_PICTURE";
export const REMOVE_PICTURE = "REMOVE_PICTURE";
export const SORT_GALLERY = "SORT_GALLERY";

export const CROP_PICTURE = "CROP_PICTURE";
export const OPEN_CROP_MODAL = "OPEN_CROP_MODAL";
export const CLOSE_CROP_MODAL = "CLOSE_CROP_MODAL";